=== Global19-atlassian-net/osiris/osiris/OsirisXML/LadderSpecifications/MarkerSet.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 rel. 3 sp1 (x64) (http://www.altova.com) by XMLSpy 2015 Professional Ed. Release 3, Installed for 13 users (with SMP from 2015-04-16 to 2016-04-16) (NIH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="KitData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Version" type="xs:string" default="2.0" minOccurs="0"/>
				<xs:element ref="Kits"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Kits">
		<xs:annotation>
			<xs:documentation>List of Marker Sets with channels, alleles, etc</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Set">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="NChannels" type="xs:int"/>
							<xs:element name="LS">
								<xs:annotation>
									<xs:documentation>Lane Standard</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="LSName" type="xs:string" maxOccurs="unbounded"/>
										<xs:element name="ChannelNo" type="xs:int"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="FileNameSuffix" type="xs:string"/>
							<xs:element name="GenotypeSuffix" type="xs:string"/>
							<xs:element name="DirectorySearchString" type="xs:string"/>
							<xs:element name="FsaChannelMap" minOccurs="0">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded">
										<xs:element name="Channel">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="KitChannelNumber" type="xs:int"/>
													<xs:element name="fsaChannelNumber" type="xs:int"/>
													<xs:element name="Color" type="xs:string" minOccurs="0"/>
													<xs:element name="DyeName" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="AllOLAllelesAccepted" type="xs:boolean" default="false" minOccurs="0"/>
							<xs:sequence maxOccurs="unbounded">
								<xs:element name="Locus">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="Name" type="xs:string"/>
											<xs:element name="Channel" type="xs:integer"/>
											<xs:element name="NoExtension" type="xs:boolean" default="false" minOccurs="0"/>
											<xs:element name="MinBP" type="xs:int">
												<xs:annotation>
													<xs:documentation>Minimum absolute locus BP for definition of extended locus:  defines acceptable extra-ladder alleles</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="MaxBP" type="xs:int">
												<xs:annotation>
													<xs:documentation>Maximum absolute locus BP for definition of extended locus:  defines acceptable extra-ladder alleles</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:choice>
												<xs:annotation>
													<xs:documentation>Only one of these pairs of values is needed.  Prefer 2nd set.</xs:documentation>
												</xs:annotation>
												<xs:sequence>
													<xs:element name="MinGridLSIndex">
														<xs:annotation>
															<xs:documentation>Legacy value.  Prefer MinGridLSBasePair below</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:double">
																<xs:minInclusive value="1.0"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="MaxGridLSIndex">
														<xs:annotation>
															<xs:documentation>Legacy value.  Prefer MaxGridLSBasePair below</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:double">
																<xs:minInclusive value="1.0"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
												<xs:sequence>
													<xs:element name="MinGridLSBasePair" type="xs:double">
														<xs:annotation>
															<xs:documentation>Minimum ILS BP to define ladder locus:  for margin of safety, choose somewhat lower than minimum ladder peak</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="MaxGridLSBasePair" type="xs:double">
														<xs:annotation>
															<xs:documentation>Maximum ILS BP to define ladder locus:  for margin of safety, choose somewhat larger than maximum ladder peak</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:choice>
											<xs:element name="CoreRepeatNumber" type="xs:integer" minOccurs="0"/>
											<xs:element name="YLinked" type="xs:boolean" default="false" minOccurs="0"/>
											<xs:element name="MaxExpectedAlleles" type="xs:int" default="2" minOccurs="0"/>
											<xs:element name="MinExpectedAlleles" type="xs:int" default="1" minOccurs="0"/>
											<xs:element name="LadderAlleles">
												<xs:complexType>
													<xs:sequence maxOccurs="unbounded">
														<xs:element name="Allele">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="Name" type="xs:string"/>
																	<xs:element name="CurveNo" type="xs:integer" minOccurs="0"/>
																	<xs:element name="BP" type="xs:integer"/>
																	<xs:element name="RelativeHeight" type="xs:string" minOccurs="0"/>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="OffLadderAlleles" minOccurs="0">
												<xs:complexType>
													<xs:sequence maxOccurs="unbounded">
														<xs:element name="OLAllele">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="Name" type="xs:string"/>
																	<xs:element name="BP" type="xs:integer"/>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Global19-atlassian-net/osiris/osiris/OsirisXML/LadderSpecifications/LaneStandardOnly_3_LadderInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<KitData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MarkerSet.xsd">
  <Version>2.0</Version>
  <Kits>
    <Set>
      <Name>LaneStandardOnly_3</Name>
      <LadderFree>true</LadderFree>
      <NChannels>3</NChannels>
      <ILS>
		<AllLaneStandards>true</AllLaneStandards>
        <ChannelNo>3</ChannelNo>
      </ILS>
      <FileNameSuffix>LANESTANDARDONLY3</FileNameSuffix>
      <GenotypeSuffix>LANESTANDARDONLY3</GenotypeSuffix>
      <DirectorySearchString>LANESTANDARDONLY3</DirectorySearchString>
      <FsaChannelMap>
        <Channel>
          <KitChannelNumber>1</KitChannelNumber>
          <fsaChannelNumber>1</fsaChannelNumber>
          <Color>BLUE</Color>
          <DyeName>6-FAM</DyeName>
        </Channel>
        <Channel>
          <KitChannelNumber>2</KitChannelNumber>
          <fsaChannelNumber>2</fsaChannelNumber>
          <Color>GREEN</Color>
          <DyeName>VIC</DyeName>
        </Channel>
        <Channel>
          <KitChannelNumber>3</KitChannelNumber>
          <fsaChannelNumber>4</fsaChannelNumber>
          <Color>ORANGE</Color>
          <DyeName>LIZ</DyeName>
        </Channel>
      </FsaChannelMap>
      <Locus>
        <Name>Channel1</Name>
        <Channel>1</Channel>
        <MinBP>1</MinBP>
        <MaxBP>400</MaxBP>
        <MinGridLSBasePair>60.0</MinGridLSBasePair>
        <MaxGridLSBasePair>1200.0</MaxGridLSBasePair>
        <LadderAlleles>
          <Allele>
            <Name>11</Name>
            <CurveNo>9</CurveNo>
            <BP>156</BP>
            <RelativeHeight>MH</RelativeHeight>
          </Allele>
          <Allele>
            <Name>12</Name>
            <CurveNo>10</CurveNo>
            <BP>160</BP>
            <RelativeHeight>MH</RelativeHeight>
          </Allele>
        </LadderAlleles>
      </Locus>
      <Locus>
        <Name>Channel2</Name>
        <Channel>2</Channel>
        <MinBP>1</MinBP>
        <MaxBP>400</MaxBP>
        <MinGridLSBasePair>60.0</MinGridLSBasePair>
        <MaxGridLSBasePair>1200.0</MaxGridLSBasePair>
        <LadderAlleles>
          <Allele>
            <Name>11</Name>
            <CurveNo>9</CurveNo>
            <BP>156</BP>
            <RelativeHeight>MH</RelativeHeight>
          </Allele>
          <Allele>
            <Name>12</Name>
            <CurveNo>10</CurveNo>
            <BP>160</BP>
            <RelativeHeight>MH</RelativeHeight>
          </Allele>
        </LadderAlleles>
      </Locus>
    </Set>
  </Kits>
</KitData>

=== Global19-atlassian-net/osiris/osiris/OsirisXML/LadderSpecifications/RyanClarkeCannabis_LadderInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<KitData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MarkerSet.xsd">
	<Version>2.0</Version>
	<Kits>
		<Set>
			<Name>Cannabis</Name>
			<NChannels>2</NChannels>
			<ILS>
			<LS>
				<LSName>ABI-ROX500</LSName>
			</LS>
				<ChannelNo>2</ChannelNo>
			</ILS>
			<FileNameSuffix>cannabis</FileNameSuffix>
			<GenotypeSuffix>cannabis</GenotypeSuffix>
			<DirectorySearchString>cannabis</DirectorySearchString>
			<FsaChannelMap>
				<Channel>
					<KitChannelNumber>1</KitChannelNumber>
					<fsaChannelNumber>3</fsaChannelNumber>
					<Color>YELLOW</Color>
					<DyeName>NED</DyeName>
				</Channel>
				<Channel>
					<KitChannelNumber>2</KitChannelNumber>
					<fsaChannelNumber>4</fsaChannelNumber>
					<Color>RED</Color>
					<DyeName>ROX</DyeName>
				</Channel>
			</FsaChannelMap>
			<Locus>
				<Name>NMI01</Name>
				<Channel>1</Channel>
				<MinBP>122</MinBP>
				<MaxBP>356</MaxBP>
				<MinGridLSBasePair>123.</MinGridLSBasePair>
				<MaxGridLSBasePair>344.</MaxGridLSBasePair>
				<CoreRepeatNumber>6</CoreRepeatNumber>
				<LadderAlleles>
					<Allele>
						<Name>2</Name>
						<CurveNo>10</CurveNo>
						<BP>128</BP>
					</Allele>
					<Allele>
						<Name>16.1</Name>
						<CurveNo>15</CurveNo>
						<BP>213</BP>
					</Allele>
					<Allele>
						<Name>22.1</Name>
						<CurveNo>20</CurveNo>
						<BP>249</BP>
					</Allele>
					<Allele>
						<Name>23</Name>
						<CurveNo>25</CurveNo>
						<BP>254</BP>
					</Allele>
					<Allele>
						<Name>26</Name>
						<CurveNo>30</CurveNo>
						<BP>272</BP>
					</Allele>
					<Allele>
						<Name>28</Name>
						<CurveNo>35</CurveNo>
						<BP>284</BP>
					</Allele>
					<Allele>
						<Name>30.1</Name>
						<CurveNo>40</CurveNo>
						<BP>297</BP>
					</Allele>
				</LadderAlleles>
			</Locus>
		</Set>
	</Kits>
</KitData>

=== Global19-atlassian-net/osiris/osiris/OsirisXML/LadderSpecifications/NIDDKFragileX1_LadderInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<KitData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="MarkerSet.xsd">
	<Version>2.0</Version>
	<Kits>
		<Set>
			<Name>NIDDKFragileX1</Name>
			<NChannels>2</NChannels>
			<LS>
				<LSName>ABI-LIZ1200</LSName>
				<LSName>ABI-LIZ-60-1200</LSName>
				<LSName>ABI-LIZ-100-1200</LSName>
				<LSName>ABI-LIZ-120-1200</LSName>
				<ChannelNo>2</ChannelNo>
			</LS>
			<FileNameSuffix>NFX1</FileNameSuffix>
			<GenotypeSuffix>NFX1</GenotypeSuffix>
			<DirectorySearchString>NFX1</DirectorySearchString>
			<FsaChannelMap>
				<Channel>
					<KitChannelNumber>1</KitChannelNumber>
					<fsaChannelNumber>1</fsaChannelNumber>
				</Channel>
				<Channel>
					<KitChannelNumber>2</KitChannelNumber>
					<fsaChannelNumber>5</fsaChannelNumber>
				</Channel>
			</FsaChannelMap>
			<AllOLAllelesAccepted>true</AllOLAllelesAccepted>
			<Locus>
				<Name>Left</Name>
				<Channel>1</Channel>
				<MinBP>100</MinBP>
				<MaxBP>295</MaxBP>
				<MinGridLSBasePair>146.4</MinGridLSBasePair>
				<MaxGridLSBasePair>232.0</MaxGridLSBasePair>
				<CoreRepeatNumber>3</CoreRepeatNumber>
				<MaxExpectedAlleles>12</MaxExpectedAlleles>
				<MinExpectedAlleles>1</MinExpectedAlleles>
				<LadderAlleles>
					<Allele>
						<Name>30</Name>
						<CurveNo>2</CurveNo>
						<BP>140</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>					
					<Allele>
						<Name>31</Name>
						<CurveNo>3</CurveNo>
						<BP>143</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>32</Name>
						<CurveNo>4</CurveNo>
						<BP>146</BP>
						<RelativeHeight>MH</RelativeHeight>
					</Allele>
					<Allele>
						<Name>41</Name>
						<CurveNo>5</CurveNo>
						<BP>170</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>42</Name>
						<CurveNo>6</CurveNo>
						<BP>173</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>43</Name>
						<CurveNo>7</CurveNo>
						<BP>176</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>48</Name>
						<CurveNo>8</CurveNo>
						<BP>188</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>49</Name>
						<CurveNo>9</CurveNo>
						<BP>191</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>50</Name>
						<CurveNo>10</CurveNo>
						<BP>194</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>55</Name>
						<CurveNo>11</CurveNo>
						<BP>206</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>56</Name>
						<CurveNo>12</CurveNo>
						<BP>209</BP>
						<RelativeHeight>MH</RelativeHeight>
					</Allele>
					<Allele>
						<Name>57</Name>
						<CurveNo>13</CurveNo>
						<BP>212</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>58</Name>
						<CurveNo>14</CurveNo>
						<BP>215</BP>
						<RelativeHeight>MH</RelativeHeight>
					</Allele>
				</LadderAlleles>
			</Locus>
			<Locus>
				<Name>Right</Name>
				<Channel>1</Channel>
				<MinBP>293</MinBP>
				<MaxBP>900</MaxBP>
				<MinGridLSBasePair>515.0</MinGridLSBasePair>
				<MaxGridLSBasePair>539.0</MaxGridLSBasePair>
				<CoreRepeatNumber>3</CoreRepeatNumber>
				<MaxExpectedAlleles>12</MaxExpectedAlleles>
				<MinExpectedAlleles>1</MinExpectedAlleles>
				<LadderAlleles>
					<Allele>
						<Name>156</Name>
						<CurveNo>3</CurveNo>
						<BP>516</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>157</Name>
						<CurveNo>4</CurveNo>
						<BP>519</BP>
						<RelativeHeight>MH</RelativeHeight>
					</Allele>
					<Allele>
						<Name>158</Name>
						<CurveNo>5</CurveNo>
						<BP>522</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>159</Name>
						<CurveNo>6</CurveNo>
						<BP>525</BP>
						<RelativeHeight>H</RelativeHeight>
					</Allele>
					<Allele>
						<Name>160</Name>
						<CurveNo>7</CurveNo>
						<BP>528</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>161</Name>
						<CurveNo>8</CurveNo>
						<BP>531</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>162</Name>
						<CurveNo>9</CurveNo>
						<BP>534</BP>
						<RelativeHeight>M</RelativeHeight>
					</Allele>
					<Allele>
						<Name>163</Name>
						<CurveNo>10</CurveNo>
						<BP>537</BP>
						<RelativeHeight>MH</RelativeHeight>
					</Allele>
				</LadderAlleles>
			</Locus>
		</Set>
	</Kits>
</KitData>
