=== Global19-atlassian-net/osiris/osiris/OsirisXML/ArtifactLabelsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2014 sp1 (x64) (http://www.altova.com) by NCBI User (National Library of Medicine) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="ArtifactLabels">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="SubGroup">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Label" type="xs:string"/>
							<xs:element name="Display" type="xs:string"/>
							<xs:element name="Priority" type="xs:integer"/>
							<xs:sequence maxOccurs="unbounded">
								<xs:element name="MsgName" type="xs:string"/>
							</xs:sequence>
							<xs:sequence minOccurs="0" maxOccurs="unbounded">
								<xs:element name="SearchString"/>
							</xs:sequence>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Global19-atlassian-net/osiris/osiris/OsirisXML/ArtifactLabels.xml
<?xml version="1.0" encoding="UTF-8"?>
<ArtifactLabels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/goorrob/Documents/GitHub/osiris/OsirisXML/ArtifactLabelsSchema.xsd">
	<SubGroup>
		<Label>Pull-up</Label>
		<Display>PU</Display>
		<Priority>1</Priority>
		<MsgName>smPullupAtExtraneousILSPeak</MsgName>
    <MsgName>smLaserOffScalePullupOrCraterNotPrimary</MsgName>
    <MsgName>smPullUp</MsgName>
    <MsgName>smInterlocusPullUp</MsgName>
    <MsgName>smInterlocusPullUpWithPoorFit</MsgName>
    <MsgName>smSigmoidalPullup</MsgName>
    <SearchString>pull.?up</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>LaserOffScale</Label>
		<Display>LO</Display>
		<Priority>2</Priority>
		<MsgName>smLaserOffScalePullupOrCraterNotPrimary</MsgName>
		<MsgName>smLaserOffScalePrimary</MsgName>
		<MsgName>smLaserOffScaleNoInterchannelLink</MsgName>
    <SearchString>laser.?off.?scale</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>PoorPeakMorphology</Label>
		<Display>MO</Display>
		<Priority>3</Priority>
		<MsgName>smCurveFitMarginal</MsgName>
		<MsgName>smSpike</MsgName>
		<MsgName>smBlob</MsgName>
		<MsgName>smCurveFitFailed</MsgName>
		<MsgName>smPoorPeakMorphology</MsgName>
		<MsgName>smAmbiguousInterlocusWithPoorMorphology</MsgName>
    <SearchString>morphology</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>Stutter</Label>
		<Display>ST</Display>
		<Priority>4</Priority>
		<MsgName>smStutter</MsgName>
		<MsgName>smBaselineRelativeStutter</MsgName>
    <SearchString>stutter</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>Adenylation</Label>
		<Display>AD</Display>
		<Priority>5</Priority>
		<MsgName>smAdenylation</MsgName>
		<MsgName>smBaselineRelativeAdenylation</MsgName>
    <SearchString>adenylation</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>AmgiguousExtendedLocus</Label>
		<Display>AM</Display>
		<Priority>6</Priority>
		<MsgName>smAmbiguousInterlocus</MsgName>
		<MsgName>smAmbiguousInterlocusWithPoorMorphology</MsgName>
		<MsgName>smAmbiguousCoreVsExtendedRight</MsgName>
		<MsgName>smPossibleAmbiguousInterlocusAssignedToLocus</MsgName>
    <SearchString>amgiguous.?extended.?locus</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>ExcessiveResidual</Label>
		<Display>ER</Display>
		<Priority>7</Priority>
		<MsgName>smAlleleHasExcessiveResidual</MsgName>
    <SearchString>residual</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>ExcessiveResidualDisplacement</Label>
		<Display>ERD</Display>
		<Priority>8</Priority>
		<MsgName>smExcessiveResidualDisplacement</MsgName>
		<MsgName>smExcessiveResidualDisplacementLeft</MsgName>
		<MsgName>smExcessiveResidualDisplacementRight</MsgName>
    <SearchString>residual.*displacement</SearchString>
	</SubGroup>
	<SubGroup>
		<Label>PrimaryPull-up</Label>
		<Display>PPU</Display>
		<Priority>9</Priority>
		<MsgName>smPrimaryInterchannelLink</MsgName>
		<MsgName>smLaserOffScalePrimary</MsgName>
    <SearchString>primary.*pull.?up</SearchString>
	</SubGroup>
</ArtifactLabels>
