=== Global19-atlassian-net/osiris/osiris/OsirisXML/NamedxmlConfigurations/StandardSettingsV4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 sp1 (x64) (http://www.altova.com) by NCBI_User (National Library of Medicine) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="StandardSettings">
		<xs:annotation>
			<xs:documentation>Comment describing your root element; this schema is for a marker set dependent standard settings file</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Version" type="xs:string" default="4.0" minOccurs="0"/>
				<xs:element ref="AlgorithmParameters"/>
				<xs:element ref="StandardParameters"/>
				<xs:element name="StdMarkerSetSpecifications" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:annotation>
								<xs:documentation>We only allow one marker set here because each std settings file is marker set specific</xs:documentation>
							</xs:annotation>
							<xs:element name="StdMarkerSetCollection">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="MarkerSetName" type="xs:string" minOccurs="0"/>
										<xs:element ref="PositiveControls" minOccurs="0"/>
										<xs:element name="StandardOffLadderAlleles" type="LocusCollection" minOccurs="0"/>
										<xs:element name="StandardTrialleles" type="LocusCollection" minOccurs="0"/>
										<xs:element name="StdPosCtrlTrialleles" type="LocusCollection" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="PositiveControls">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="PositiveControl">
					<xs:annotation>
						<xs:documentation>Each positive control has a file name containing a specific synonym</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Name"/>
							<xs:element name="Loci" type="LocusCollection"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AlgorithmParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CurveFitParameters"/>
				<xs:element ref="LaneStandardSearch"/>
				<xs:element ref="LadderLocusSearch"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StandardParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MsgDoubleResolution" type="xs:integer" default="10">
					<xs:annotation>
						<xs:documentation>Number of digits for output of floating point numbers</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MinSigmaForDyeBlob" type="xs:double" default="6.0">
					<xs:annotation>
						<xs:documentation>Dye blobs must have this sigma, or more</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SecondaryContentLimitFraction" default="0.9">
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="0"/>
							<xs:maxExclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MinFractionExpectedPeakWidth" default="0.6">
					<xs:annotation>
						<xs:documentation>Tests for poor morphology</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:maxExclusive value="1"/>
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MaxMultipleExpectedPeakWidth" default="1.6">
					<xs:annotation>
						<xs:documentation>Tests for poor morphology</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="1" fixed="false"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="WidthMatchFraction" default="0.1">
					<xs:annotation>
						<xs:documentation>Fraction of combined sigmas of two curves that should be the 'same' width</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="0"/>
							<xs:maxExclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MaxSpikeWidth" type="xs:decimal">
					<xs:annotation>
						<xs:documentation>Max sigma for a peak to be considered a spike</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CraterSigmaMultiple" type="xs:double" default="2.0">
					<xs:annotation>
						<xs:documentation>Number of sigmas used for distance between peaks to determine if the two form a crater</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Synonym" type="xs:string">
		<xs:annotation>
			<xs:documentation>All substrings are case independent</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="Name" type="xs:string"/>
	<xs:element name="Locus">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name">
					<xs:annotation>
						<xs:documentation>Locus name</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="Allele">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="Name"/>
								<xs:element name="BioID" type="xs:int">
									<xs:annotation>
										<xs:documentation>Base pair relative to named locus</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ControlSearchBounds">
		<xs:sequence>
			<xs:element name="MaxSpacingMultiple" type="xs:double"/>
			<xs:element name="MinSpacingMultiple" type="xs:double"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="CurveFitParameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NoiseThreshold" type="xs:double" default="400">
					<xs:annotation>
						<xs:documentation>Value 400 allows peak detection of ~20 RFU or more</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="WindowWidth" type="xs:integer" default="9">
					<xs:annotation>
						<xs:documentation>Value 9 allows peak spacing discernment of less than 1 base pair</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MinFitForNormalPeak" default="0.95">
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="0"/>
							<xs:maxInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="TriggerFitForArtifact" default="0.97">
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="0"/>
							<xs:maxExclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AbsoluteMinimumFit" type="xs:double" default="0.85"/>
				<xs:element name="TestForNegSecondaryContent" type="xs:boolean" default="false"/>
				<xs:element name="ParametricFitTolerance" default="0.999995">
					<xs:annotation>
						<xs:documentation>Termination criterion for iterative curve fit prior to maximum iterations</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="0"/>
							<xs:maxExclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="NumberOfIntegrationSteps" type="xs:integer" default="50">
					<xs:annotation>
						<xs:documentation>For performing numerical integrations of Gaussian curves</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SigmaTolerance" type="xs:double" default="0.00015">
					<xs:annotation>
						<xs:documentation>Termination criterion for sigma fit prior to max iterations; delta sigma threshold</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SigmaWidth" type="xs:double" default="10.0">
					<xs:annotation>
						<xs:documentation>Number of sigmas to left and right of mean in standard constructor of Gaussians</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MaximumIterations" type="xs:integer" default="5">
					<xs:annotation>
						<xs:documentation>Max number of iterations allowed in search for best curve fit</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SigmaRatio" type="xs:double" default="4.0">
					<xs:annotation>
						<xs:documentation>Ratio of 2nd Gaussian sigma to 1st in Double Gaussian</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="InterSampleSpacing" type="xs:double" default="1">
					<xs:annotation>
						<xs:documentation>Number of seconds per measurement</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SignatureSigma" type="xs:double" default="2.0">
					<xs:annotation>
						<xs:documentation>Starting base sigma for signature Double Gaussian; deliberately chosen below expected true value</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="BlobDegree" type="xs:integer" default="6">
					<xs:annotation>
						<xs:documentation>Degree of Super Gaussian used to fit blob artifacts</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MinDistanceBetweenPeaks" type="xs:double" default="4.0">
					<xs:annotation>
						<xs:documentation>Two peaks within this distance are not considered distinct; only the best fit is kept</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="PeakFractionForEndPtTest" default="0.25">
					<xs:annotation>
						<xs:documentation>Tests for 'flat' fit; tails compared to this fraction of peak</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:double">
							<xs:minExclusive value="0"/>
							<xs:maxExclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="PeakLevelForEndPtTest" type="xs:double" default="60.0">
					<xs:annotation>
						<xs:documentation>Tests for 'flat' fits; fractiion above compared to peak less this level</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="LowTailHeightThreshold" type="xs:double" default="0.1">
					<xs:annotation>
						<xs:documentation>Fraction of peak height for (left) tail in scanning for end of data interval</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="LowTailSlopeThreshold" type="xs:double" default="0.1">
					<xs:annotation>
						<xs:documentation>Fraction of peak slope (via linear regression) for (left) tail in scanning for end of data interval</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MinSamplesForSlopeRegression" default="3">
					<xs:annotation>
						<xs:documentation>Minimum number of samples to use to estimate slope using linear regression - preferably, algoriithm uses more than this number</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minInclusive value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LaneStandardSearch">
		<xs:annotation>
			<xs:documentation>Subset selection search parameters</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AcceptanceFactorOfMaxPeak" type="xs:double" default="0.34">
					<xs:annotation>
						<xs:documentation>Filter for initial 'junk' at beginning - reject peaks above this fraction of max peak</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="EndTestFactor" type="xs:double" default="0.335">
					<xs:annotation>
						<xs:documentation>Used to test validity of max peak as defining 'junk' - last peak on right must be less than this fraction of max peak</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SkipFractionOfInitialPeaks" type="xs:double" default="0.4">
					<xs:annotation>
						<xs:documentation>Skip this proportion of initial peaks on left when calculating max peak to be used with relative height criteria (not the same max peak as above)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MinCorrelationForRecursiveSearch" type="xs:double" default="0.98">
					<xs:annotation>
						<xs:documentation>During recursive search, use this correlation to weed out unlikely subsets - deliberately set 'low'</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MaxStartPtsForPartialSearch" type="xs:integer" default="6">
					<xs:annotation>
						<xs:documentation>In the absence of relative height info, use this number (maximum) to initiate left and right search, and then add peaks in the middle</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="BeginAnalysisProportion" type="xs:double" default="0.75">
					<xs:annotation>
						<xs:documentation>The 'begin analysis' time is set to this fraction times the mean of the first peak plus 1 minus this fraction times the 'end of the junk'</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="LaneStandardSearchSpacing" type="ControlSearchBounds">
					<xs:annotation>
						<xs:documentation>For selection of correct lane standard peaks from set of candidate peaks</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="CorrelationThresholds">
					<xs:annotation>
						<xs:documentation>Correlation with ideal (after quadratic transformation) required for lane std acceptance</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="ILSSpecificThreshold">
								<xs:annotation>
									<xs:documentation>Synonym gives substring in lane standard name, such as "ABI" or "Promega"</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Synonym"/>
										<xs:element name="CorrelationWiithIdeal" type="xs:double"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LadderLocusSearch">
		<xs:annotation>
			<xs:documentation>Subset selection search parameters</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LadderLociMinimumCorrelationWithIdeal" type="xs:double" default="0.999">
					<xs:annotation>
						<xs:documentation>Correlation with ideal required for locus acceptance</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="LadderLocusSearchSpacing" type="ControlSearchBounds">
					<xs:annotation>
						<xs:documentation>For selection of correct locus peaks from set of candidate peaks</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="MaxStartPtsForPartialSearch" type="xs:integer" default="6">
					<xs:annotation>
						<xs:documentation>In the absence of relative height info, use this number (maximum) to initiate left and right search, and then add peaks in the middle</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="LocusCollection">
		<xs:sequence maxOccurs="unbounded">
			<xs:element ref="Locus"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Global19-atlassian-net/osiris/osiris/OsirisXML/NamedxmlConfigurations/iPLEXSTRLIZ500less250/iPlexLIZ500less250_StdSettings.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp2 (http://www.altova.com)-->

<StandardSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\StandardSettingsV4.xsd">

	<AlgorithmParameters>

		<CurveFitParameters>

			<NoiseThreshold>300</NoiseThreshold>

			<WindowWidth>9</WindowWidth>

			<MinFitForNormalPeak>0.98</MinFitForNormalPeak>

			<TriggerFitForArtifact>0.99</TriggerFitForArtifact>

			<AbsoluteMinimumFit>0.85</AbsoluteMinimumFit>

			<TestForNegSecondaryContent>false</TestForNegSecondaryContent>

			<ParametricFitTolerance>0.999995</ParametricFitTolerance>

			<NumberOfIntegrationSteps>50</NumberOfIntegrationSteps>

			<SigmaTolerance>0.00015</SigmaTolerance>

			<SigmaWidth>10.0</SigmaWidth>

			<MaximumIterations>5</MaximumIterations>

			<SigmaRatio>4.5</SigmaRatio>

			<InterSampleSpacing>1</InterSampleSpacing>

			<SignatureSigma>2.0</SignatureSigma>

			<BlobDegree>6</BlobDegree>

			<MinDistanceBetweenPeaks>1.5</MinDistanceBetweenPeaks>

			<PeakFractionForEndPtTest>0.25</PeakFractionForEndPtTest>

			<PeakLevelForEndPtTest>60.0</PeakLevelForEndPtTest>

			<LowTailHeightThreshold>0.1</LowTailHeightThreshold>

			<LowTailSlopeThreshold>0.1</LowTailSlopeThreshold>

			<MinSamplesForSlopeRegression>4</MinSamplesForSlopeRegression>

		</CurveFitParameters>

		<LaneStandardSearch>

			<AcceptanceFactorOfMaxPeak>0.34</AcceptanceFactorOfMaxPeak>

			<EndTestFactor>0.335</EndTestFactor>

			<SkipFractionOfInitialPeaks>0.4</SkipFractionOfInitialPeaks>

			<MinCorrelationForRecursiveSearch>0.98</MinCorrelationForRecursiveSearch>

			<MaxStartPtsForPartialSearch>6</MaxStartPtsForPartialSearch>

			<BeginAnalysisProportion>0.75</BeginAnalysisProportion>

			<LaneStandardSearchSpacing>

				<MaxSpacingMultiple>1.5</MaxSpacingMultiple>

				<MinSpacingMultiple>0.6</MinSpacingMultiple>

			</LaneStandardSearchSpacing>

			<CorrelationThresholds>

				<ILSSpecificThreshold>

					<Synonym>iPLEXSTRLIZ500less250</Synonym>

					<CorrelationWiithIdeal>0.995</CorrelationWiithIdeal>

				</ILSSpecificThreshold>

			</CorrelationThresholds>

		</LaneStandardSearch>

		<LadderLocusSearch>

			<LadderLociMinimumCorrelationWithIdeal>0.999</LadderLociMinimumCorrelationWithIdeal>

			<LadderLocusSearchSpacing>

				<MaxSpacingMultiple>1.2</MaxSpacingMultiple>

				<MinSpacingMultiple>0.7</MinSpacingMultiple>

			</LadderLocusSearchSpacing>

			<MaxStartPtsForPartialSearch>6</MaxStartPtsForPartialSearch>

		</LadderLocusSearch>

	</AlgorithmParameters>

	<StandardParameters>

		<MsgDoubleResolution>10</MsgDoubleResolution>

		<MinSigmaForDyeBlob>6.0</MinSigmaForDyeBlob>

		<SecondaryContentLimitFraction>0.9</SecondaryContentLimitFraction>

		<MinFractionExpectedPeakWidth>0.6</MinFractionExpectedPeakWidth>

		<MaxMultipleExpectedPeakWidth>1.6</MaxMultipleExpectedPeakWidth>

		<WidthMatchFraction>0.1</WidthMatchFraction>

		<MaxSpikeWidth>1.0</MaxSpikeWidth>

		<CraterSigmaMultiple>2.0</CraterSigmaMultiple>

	</StandardParameters>

	<StdMarkerSetSpecifications>

		<StdMarkerSetCollection>

			<MarkerSetName>iPLEXSTRLIZ500less250</MarkerSetName>

			<PositiveControls>

				<PositiveControl>

					<Name>Positive</Name>

					<Loci>

						<Locus>

							<Name>AMEL</Name>

							<Allele>

								<Name>1</Name>

								<BioID>81</BioID>

							</Allele>

							<Allele>
  
								<Name>2</Name>

								<BioID>84</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D3S1358</Name>

							<Allele>

								<Name>15</Name>

								<BioID>124</BioID>

							</Allele>
  
							<Allele>

								<Name>17</Name>

								<BioID>132</BioID>
  
              </Allele>

            </Locus>

						<Locus>

							<Name>TH01</Name>

							<Allele>

								<Name>6</Name>

								<BioID>163</BioID>

							</Allele>

							<Allele>

								<Name>9.3</Name>

								<BioID>178</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D12S391</Name>

							<Allele>

								<Name>21</Name>

								<BioID>239</BioID>

							</Allele>

							<Allele>

								<Name>23</Name>

								<BioID>247</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D1S1656</Name>

							<Allele>

								<Name>11</Name>

								<BioID>290</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D10S1248</Name>

							<Allele>

								<Name>13</Name>

								<BioID>368</BioID>

							</Allele>

							<Allele>

								<Name>15</Name>

								<BioID>376</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D2S441</Name>

							<Allele>

								<Name>9</Name>

								<BioID>91</BioID>

							</Allele>

							<Allele>

								<Name>13</Name>

								<BioID>107</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D7S820</Name>

							<Allele>

								<Name>10</Name>

								<BioID>157</BioID>

							</Allele>

							<Allele>

								<Name>12</Name>

								<BioID>165</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D13S317</Name>

							<Allele>

								<Name>11</Name>

								<BioID>208</BioID>

							</Allele>

							<Allele>

								<Name>12</Name>

								<BioID>212</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>FGA</Name>

							<Allele>

								<Name>20</Name>

								<BioID>267</BioID>

							</Allele>

							<Allele>

								<Name>26</Name>

								<BioID>291</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>TPOX</Name>

							<Allele>

								<Name>8</Name>

								<BioID>87</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D18S51</Name>

							<Allele>

								<Name>12</Name>

								<BioID>149</BioID>

							</Allele>

							<Allele>

								<Name>14</Name>

								<BioID>157</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D16S539</Name>

							<Allele>

								<Name>9</Name>

								<BioID>230</BioID>

							</Allele>
  
							<Allele>

								<Name>11</Name>

								<BioID>238</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>D8S1179</Name>

							<Allele>

								<Name>9</Name>

								<BioID>276</BioID>

							</Allele>
  
						<Allele>

								<Name>10</Name>

								<BioID>280</BioID>

							</Allele>

						</Locus>

						<Locus>

							<Name>CSF1PO</Name>

							<Allele>

								<Name>9</Name>

								<BioID>338</BioID>

							</Allele>

							<Allele>

								<Name>11</Name>

								<BioID>346</BioID>

							</Allele>

						</Locus>
  
						<Locus>

							<Name>D5S818</Name>

							<Allele>

								<Name>10</Name>

								<BioID>392</BioID>

							</Allele>

							<Allele>

								<Name>11</Name>

								<BioID>396</BioID>

							</Allele>

						</Locus>
  
						<Locus>

							<Name>vWA</Name>

							<Allele>

								<Name>15</Name>

								<BioID>124</BioID>

							</Allele>

							<Allele>

								<Name>18</Name>

								<BioID>136</BioID>

							</Allele>

						</Locus>
  
						<Locus>

							<Name>D21S11</Name>

							<Allele>

								<Name>27</Name>

								<BioID>179</BioID>

							</Allele>

							<Allele>

								<Name>28</Name>

								<BioID>183</BioID>

							</Allele>

						</Locus>
  
            <Locus>

							<Name>SE33O</Name>

							<Allele>

								<Name>17</Name>

								<BioID>302</BioID>

							</Allele>

							<Allele>

								<Name>21.2</Name>

								<BioID>320</BioID>

							</Allele>
  
							</Locus>
  
					</Loci>

				</PositiveControl>

			</PositiveControls>

		</StdMarkerSetCollection>

	</StdMarkerSetSpecifications>

</StandardSettings>
